TASK13: 
  name: VisualEntailment
  type: VL-tri-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 13
  dataroot: datasets/visual_entailment/
  features_h5path1: datasets/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 56
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: dev
  lr: 0.00002
  num_epoch: 20
